development:
  adapter: postgresql
  encoding: unicode
  database: rails-sample
  pool: 5
  username: eiji

test:
  adapter: postgresql
  encoding: unicode
  database: rails-sample
  pool: 5
  username: eiji

production:
  adapter: postgresql
  encoding: unicode
  database: rails-sample
  pool: 5
  username: eiji
